### ISSUE TITLE
Imágenes del menú

### ISSUE THREAD

**Issue by mpaulazzv** [mpaulazzv/ProMediApp#1]
Cuando puse el menú como un componente, las imágenes ya no se muestran y ya he probado muchas formas de escribir las rutas a las imágenes

**Comment by Volkamr** [comment]
Se logro solucionar haciendo referencia a las rutas del servidor http

- _http://127.0.0.1:3000/src/assets/imagen.svg_

![nav](https://github.com/user-attachments/assets/d68f5d0f-3db3-4b8a-8461-98788a58b9a2)
